package snapmaker

import "testing"

func TestParseGcodeFilamentUsageCommaSeparated(t *testing.T) {
	content := []byte(`; generated by OrcaSlicer
; filament used [g] = 12.34, 5.67
M104 S200`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 12.34 {
		t.Fatalf("expected toolhead 0 to use 12.34g, got %v", usage[0])
	}
	if usage[1] != 5.67 {
		t.Fatalf("expected toolhead 1 to use 5.67g, got %v", usage[1])
	}
}

func TestParseGcodeFilamentUsageOrcaExtruder1(t *testing.T) {
	content := []byte(`; generated by OrcaSlicer
; filament used [g] = 0, 9.15, 0, 0`)

	resolution := ResolveFilamentUsage(content, nil)
	if resolution.Source != "gcode_comma" {
		t.Fatalf("expected source gcode_comma, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 to use 9.15g, got %v", resolution.Usage)
	}
	if _, ok := resolution.Usage[0]; ok {
		t.Fatal("extruder 0 should not have usage")
	}
}

func TestParseGcodeFilamentUsageTotal(t *testing.T) {
	content := []byte(`; total filament used [g] = 42.5`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 42.5 {
		t.Fatalf("expected toolhead 0 to use 42.5g, got %v", usage[0])
	}
}

func TestParseGcodeFilamentUsageSingleToolhead(t *testing.T) {
	content := []byte(`; filament used [g]=9.87`)

	resolution := ResolveFilamentUsage(content, nil)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected source gcode_single_extruder, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 9.87 {
		t.Fatalf("expected extruder 0 to use 9.87g, got %v", resolution.Usage[0])
	}
}

func TestParseGcodeFilamentUsageEmpty(t *testing.T) {
	usage, err := ParseGcodeFilamentUsage([]byte("; no metadata here"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 0 {
		t.Fatalf("expected empty usage map, got %v", usage)
	}
}

func TestResolveFilamentUsageMoonrakerReferencedTools(t *testing.T) {
	metadata := &FilamentUsageMetadata{
		FilamentWeightTotal: 9.15,
		ReferencedTools:     []int{1},
	}

	resolution := ResolveFilamentUsage([]byte("; no gcode metadata"), metadata)
	if resolution.Source != "moonraker_referenced_tools" {
		t.Fatalf("expected moonraker_referenced_tools, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 usage 9.15g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageMoonrakerFilamentWeights(t *testing.T) {
	metadata := &FilamentUsageMetadata{
		FilamentWeights: []float64{0, 9.15, 0, 0},
	}

	resolution := ResolveFilamentUsage([]byte("; empty"), metadata)
	if resolution.Source != "moonraker_filament_weights" {
		t.Fatalf("expected moonraker_filament_weights, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 usage, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageGcodeTakesPriorityOverMetadata(t *testing.T) {
	content := []byte(`; filament used [g] = 9.15`)
	metadata := &FilamentUsageMetadata{
		FilamentWeightTotal: 99.0,
		ReferencedTools:     []int{1},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected gcode to win, got source %s", resolution.Source)
	}
	if resolution.Usage[0] != 9.15 {
		t.Fatalf("expected extruder 0 from gcode, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsed(t *testing.T) {
	content := []byte(`; filament used [g] = 8.61`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{false, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruders_used:main" {
		t.Fatalf("expected snapmaker_extruders_used:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 8.61 {
		t.Fatalf("expected extruder 1 usage 8.61g, got %v", resolution.Usage)
	}
	if _, ok := resolution.Usage[0]; ok {
		t.Fatal("extruder 0 should not have usage after snapmaker correction")
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsedNoRemapWhenActiveIsZero(t *testing.T) {
	content := []byte(`; filament used [g] = 8.61`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{true, false, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected gcode_single_extruder, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 8.61 {
		t.Fatalf("expected extruder 0 usage, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsedCommaFormat(t *testing.T) {
	content := []byte(`; filament used [g] = 76.35, 0.00, 0.00, 0.00`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{false, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruders_used:main" {
		t.Fatalf("expected snapmaker_extruders_used:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 76.35 {
		t.Fatalf("expected extruder 1 usage 76.35g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtruderMapTable(t *testing.T) {
	content := []byte(`; filament used [g] = 76.35, 0.00, 0.00, 0.00`)
	metadata := &FilamentUsageMetadata{
		ExtruderMapTable: []int{1, 0, 2, 3},
		ExtrudersUsed:    []bool{false, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruder_map:main" {
		t.Fatalf("expected snapmaker_extruder_map:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 76.35 {
		t.Fatalf("expected extruder 1 usage 76.35g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtruderMapTableTwoColors(t *testing.T) {
	content := []byte(`; filament used [g] = 50, 30, 0, 0`)
	metadata := &FilamentUsageMetadata{
		ExtruderMapTable: []int{1, 3, 2, 0},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruder_map:main" {
		t.Fatalf("expected snapmaker_extruder_map:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 50 {
		t.Fatalf("expected extruder 1 usage 50g, got %v", resolution.Usage)
	}
	if resolution.Usage[3] != 30 {
		t.Fatalf("expected extruder 3 usage 30g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsedTwoColors(t *testing.T) {
	content := []byte(`; filament used [g] = 50, 30, 0, 0`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{false, true, false, true},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruders_used:main" {
		t.Fatalf("expected snapmaker_extruders_used:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 50 {
		t.Fatalf("expected extruder 1 usage 50g, got %v", resolution.Usage)
	}
	if resolution.Usage[3] != 30 {
		t.Fatalf("expected extruder 3 usage 30g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerIdentityMapNoRemap(t *testing.T) {
	content := []byte(`; filament used [g] = 12.34, 5.67`)
	metadata := &FilamentUsageMetadata{
		ExtruderMapTable: []int{0, 1, 2, 3},
		ExtrudersUsed:    []bool{true, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_comma" {
		t.Fatalf("expected gcode_comma without remap, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 12.34 || resolution.Usage[1] != 5.67 {
		t.Fatalf("expected unchanged usage, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsedCountMismatch(t *testing.T) {
	content := []byte(`; filament used [g] = 50, 30, 0, 0`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{true, true, true, true},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_comma" {
		t.Fatalf("expected gcode_comma without remap on count mismatch, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 50 || resolution.Usage[1] != 30 {
		t.Fatalf("expected original usage, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtruderMapTableRemapsFilamentWeights(t *testing.T) {
	metadata := &FilamentUsageMetadata{
		FilamentWeights:  []float64{76.35, 0, 0, 0},
		ExtruderMapTable: []int{1, 0, 2, 3},
	}

	resolution := ResolveFilamentUsage([]byte("; no gcode footer"), metadata)
	if resolution.Source != "snapmaker_extruder_map:main" {
		t.Fatalf("expected snapmaker_extruder_map:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 76.35 {
		t.Fatalf("expected extruder 1 usage 76.35g, got %v", resolution.Usage)
	}
}

func TestRemapSnapmakerExtruderUsageGcodeTotal(t *testing.T) {
	content := []byte(`; total filament used [g] = 42.5`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{false, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruders_used:main" {
		t.Fatalf("expected snapmaker_extruders_used:main, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 42.5 {
		t.Fatalf("expected extruder 1 usage 42.5g, got %v", resolution.Usage)
	}
}

func owlMainExtruderMapTable() []int {
	return []int{0, 1, 2, 3, 0, 0, 0, 0}
}

func owlReprintExtruderMapTable() []int {
	return []int{0, 1, 3, 3, 0, 2, 0, 0}
}

func TestScoreExtruderMapTableOwlPrefersReprint(t *testing.T) {
	logical := map[int]float64{0: 47.18, 1: 8.46, 2: 4.34, 5: 22.42}
	mainScore := scoreExtruderMapTable(logical, owlMainExtruderMapTable())
	reprintScore := scoreExtruderMapTable(logical, owlReprintExtruderMapTable())
	if reprintScore <= mainScore {
		t.Fatalf("reprint score %d should beat main score %d", reprintScore, mainScore)
	}
}

func TestSelectExtruderMapTableOwl(t *testing.T) {
	logical := map[int]float64{0: 47.18, 1: 8.46, 2: 4.34, 5: 22.42}
	_, _, source := selectExtruderMapTable(
		logical,
		owlMainExtruderMapTable(),
		owlReprintExtruderMapTable(),
		[]bool{false, false, false, false},
		[]bool{true, true, true, true},
	)
	if source != "reprint_info" {
		t.Fatalf("expected reprint_info, got %s", source)
	}
}

func TestResolveFilamentUsageSnapmakerOwlMultiMaterial(t *testing.T) {
	content := []byte(`; filament used [g] = 47.18, 8.46, 4.34, 0.00, 0.00, 22.42`)
	metadata := &FilamentUsageMetadata{
		ExtruderMapTable:        owlMainExtruderMapTable(),
		ReprintExtruderMapTable: owlReprintExtruderMapTable(),
		ExtrudersUsed:           []bool{false, false, false, false},
		ReprintExtrudersUsed:    []bool{true, true, true, true},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruder_map:reprint_info" {
		t.Fatalf("expected snapmaker_extruder_map:reprint_info, got %s", resolution.Source)
	}

	want := map[int]float64{0: 47.18, 1: 8.46, 2: 22.42, 3: 4.34}
	for k, v := range want {
		if resolution.Usage[k] != v {
			t.Fatalf("extruder %d: got %v want %v (full: %v)", k, resolution.Usage[k], v, resolution.Usage)
		}
	}
}

func TestDistributeFilamentProportionally(t *testing.T) {
	gcodeUsage := map[int]float64{0: 60, 1: 40}
	got := distributeFilamentProportionally(10, gcodeUsage)

	if got[0] != 6 || got[1] != 4 {
		t.Fatalf("expected proportional split 6g/4g, got %v", got)
	}
}

func TestScaleFilamentUsage(t *testing.T) {
	gcodeUsage := map[int]float64{0: 10}
	got := scaleFilamentUsage(gcodeUsage, 0.4)

	if got[0] != 4 {
		t.Fatalf("expected 4g at 40%% progress, got %v", got[0])
	}
}

func TestClampUnitInterval(t *testing.T) {
	if clampUnitInterval(-0.5) != 0 {
		t.Fatal("expected negative clamped to 0")
	}
	if clampUnitInterval(1.5) != 1 {
		t.Fatal("expected value above 1 clamped to 1")
	}
	if clampUnitInterval(0.42) != 0.42 {
		t.Fatal("expected in-range value unchanged")
	}
}
