package main

import "testing"

func TestParseGcodeFilamentUsageCommaSeparated(t *testing.T) {
	content := []byte(`; generated by OrcaSlicer
; filament used [g] = 12.34, 5.67
M104 S200`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 12.34 {
		t.Fatalf("expected toolhead 0 to use 12.34g, got %v", usage[0])
	}
	if usage[1] != 5.67 {
		t.Fatalf("expected toolhead 1 to use 5.67g, got %v", usage[1])
	}
}

func TestParseGcodeFilamentUsageTotal(t *testing.T) {
	content := []byte(`; total filament used [g] = 42.5`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 42.5 {
		t.Fatalf("expected toolhead 0 to use 42.5g, got %v", usage[0])
	}
}

func TestParseGcodeFilamentUsageSingleToolhead(t *testing.T) {
	content := []byte(`; filament used [g]=9.87`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 9.87 {
		t.Fatalf("expected toolhead 0 to use 9.87g, got %v", usage[0])
	}
}

func TestParseGcodeFilamentUsageEmpty(t *testing.T) {
	usage, err := ParseGcodeFilamentUsage([]byte("; no metadata here"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 0 {
		t.Fatalf("expected empty usage map, got %v", usage)
	}
}
