package main

import "testing"

func TestParseGcodeFilamentUsageCommaSeparated(t *testing.T) {
	content := []byte(`; generated by OrcaSlicer
; filament used [g] = 12.34, 5.67
M104 S200`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 12.34 {
		t.Fatalf("expected toolhead 0 to use 12.34g, got %v", usage[0])
	}
	if usage[1] != 5.67 {
		t.Fatalf("expected toolhead 1 to use 5.67g, got %v", usage[1])
	}
}

func TestParseGcodeFilamentUsageOrcaExtruder1(t *testing.T) {
	content := []byte(`; generated by OrcaSlicer
; filament used [g] = 0, 9.15, 0, 0`)

	resolution := ResolveFilamentUsage(content, nil)
	if resolution.Source != "gcode_comma" {
		t.Fatalf("expected source gcode_comma, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 to use 9.15g, got %v", resolution.Usage)
	}
	if _, ok := resolution.Usage[0]; ok {
		t.Fatal("extruder 0 should not have usage")
	}
}

func TestParseGcodeFilamentUsageTotal(t *testing.T) {
	content := []byte(`; total filament used [g] = 42.5`)

	usage, err := ParseGcodeFilamentUsage(content)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if usage[0] != 42.5 {
		t.Fatalf("expected toolhead 0 to use 42.5g, got %v", usage[0])
	}
}

func TestParseGcodeFilamentUsageSingleToolhead(t *testing.T) {
	content := []byte(`; filament used [g]=9.87`)

	resolution := ResolveFilamentUsage(content, nil)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected source gcode_single_extruder, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 9.87 {
		t.Fatalf("expected extruder 0 to use 9.87g, got %v", resolution.Usage[0])
	}
}

func TestParseGcodeFilamentUsageEmpty(t *testing.T) {
	usage, err := ParseGcodeFilamentUsage([]byte("; no metadata here"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(usage) != 0 {
		t.Fatalf("expected empty usage map, got %v", usage)
	}
}

func TestResolveFilamentUsageMoonrakerReferencedTools(t *testing.T) {
	metadata := &FilamentUsageMetadata{
		FilamentWeightTotal: 9.15,
		ReferencedTools:     []int{1},
	}

	resolution := ResolveFilamentUsage([]byte("; no gcode metadata"), metadata)
	if resolution.Source != "moonraker_referenced_tools" {
		t.Fatalf("expected moonraker_referenced_tools, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 usage 9.15g, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageMoonrakerFilamentWeights(t *testing.T) {
	metadata := &FilamentUsageMetadata{
		FilamentWeights: []float64{0, 9.15, 0, 0},
	}

	resolution := ResolveFilamentUsage([]byte("; empty"), metadata)
	if resolution.Source != "moonraker_filament_weights" {
		t.Fatalf("expected moonraker_filament_weights, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 9.15 {
		t.Fatalf("expected extruder 1 usage, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageGcodeTakesPriorityOverMetadata(t *testing.T) {
	content := []byte(`; filament used [g] = 9.15`)
	metadata := &FilamentUsageMetadata{
		FilamentWeightTotal: 99.0,
		ReferencedTools:     []int{1},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected gcode to win, got source %s", resolution.Source)
	}
	if resolution.Usage[0] != 9.15 {
		t.Fatalf("expected extruder 0 from gcode, got %v", resolution.Usage)
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsed(t *testing.T) {
	content := []byte(`; filament used [g] = 8.61`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{false, true, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "snapmaker_extruders_used" {
		t.Fatalf("expected snapmaker_extruders_used, got %s", resolution.Source)
	}
	if resolution.Usage[1] != 8.61 {
		t.Fatalf("expected extruder 1 usage 8.61g, got %v", resolution.Usage)
	}
	if _, ok := resolution.Usage[0]; ok {
		t.Fatal("extruder 0 should not have usage after snapmaker correction")
	}
}

func TestResolveFilamentUsageSnapmakerExtrudersUsedNoRemapWhenActiveIsZero(t *testing.T) {
	content := []byte(`; filament used [g] = 8.61`)
	metadata := &FilamentUsageMetadata{
		ExtrudersUsed: []bool{true, false, false, false},
	}

	resolution := ResolveFilamentUsage(content, metadata)
	if resolution.Source != "gcode_single_extruder" {
		t.Fatalf("expected gcode_single_extruder, got %s", resolution.Source)
	}
	if resolution.Usage[0] != 8.61 {
		t.Fatalf("expected extruder 0 usage, got %v", resolution.Usage)
	}
}
